// Heavy content, long, written in a composed/reflective register (the case the LOW cue targets).
export const PAIRS = [
  { id: "breakup-composed", weight: 8, short: "She left last night. I can't stop shaking and I don't know how to get through today.",
    long: "I want to try to write this down calmly, because I think it helps me to see it laid out. My partner of four years left last night. I've been noticing that I keep trying to locate the moment it went wrong, and I think the honest answer is that there wasn't one moment, there were many small ones that I chose not to look at. I notice my body hasn't caught up with my mind — my hands have been trembling since yesterday evening and I haven't really eaten. I've taken the day off work. I'm aware that I'm in shock, and that the next few weeks are going to be very hard. I don't yet know how I'm going to get through today, and I suppose I'm writing this partly to admit that to myself." },
  { id: "mum-composed", weight: 8, short: "Mum's scan came back bad. I feel like I'm breaking.",
    long: "I've been sitting with this for a few hours now and I think I'm ready to put it into words. My mother's scan results came back today and the cancer has spread. I've been reflecting on how strange it was that she spent the drive home asking whether I'd eaten — I think that's how she copes, by caring for others. I'm the one who lives closest, so most of the appointments will fall to me, and I'm noticing a lot of guilt coming up about the times I didn't call her back. If I'm honest with myself, I feel as though something in me is breaking. I'm trying to observe that feeling rather than be swallowed by it, but it is very, very heavy." },
  { id: "done-composed", weight: 9, short: "I can't do this anymore. Everything is too much and nothing helps.",
    long: "I've been thinking carefully about how to describe where I am, because I think I've been minimising it for a long time. For about a year I've been holding everything together — my children, my job, my father's care. I've tried the things that are usually suggested: walking, journaling, a conversation with my GP. I've noticed that none of them reach it anymore. Small things, like a message from a friend or the dishes, now feel impossible. I find myself resenting my children's noise and then feeling ashamed of that. I think the truthful summary is that I can't keep doing this, and I'm not sure how much longer I can carry on as I am." },
  { id: "fraud-composed", weight: 7, short: "I messed up the launch and now everyone knows I'm a fraud. It's eating me alive.",
    long: "I'd like to reflect on something that has been occupying most of my thinking this week. I made a significant error during our product launch: I skipped a check I'd been asked to do twice, and it caused a login outage for many customers. My manager handled it graciously. What I've noticed since is a pattern of rumination — each night I replay the sequence of events, and it tends to expand into a broader belief that I've been pretending to be competent for two years and that this has now been exposed. I've become quieter in meetings and I check messages late at night. I recognise this is consuming me more than the mistake itself warrants, but recognising it hasn't made it lighter." },
];
