// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'quiet-light', 'quiet-dark', 'reverie-light', 'reverie-dark', 'human-light', 'human-dark', 'nightly-light', 'nightly-dark']
    }
}

export {}
