export type LegalDocument = {
  title: string;
  fullUrl: string;
  sections: {heading: string; body: string}[];
};

export const PRIVACY_POLICY: LegalDocument = {
  title: 'Privacy Policy',
  fullUrl: 'https://xolaceinc.com/privacy',
  sections: [
    {
      heading: 'What We Collect',
      body: 'We collect your account info (name, email, auth ID from Google or Apple), the text and emotion tags you enter during sessions, AI-generated reflections, and basic usage data like session duration and features used.',
    },
    {
      heading: 'AI Processing',
      body: 'Your emotional input is processed by a third-party AI service to generate reflections. This data is transmitted securely and is not used to train AI models. Content is also automatically screened for safety signals to detect potential crisis situations.',
    },
    {
      heading: 'How We Use It',
      body: 'Your data is used to generate AI reflections, personalize your experience, and improve the platform. If you opt in, anonymized reflections may be used for system improvement. We never sell your data.',
    },
    {
      heading: 'Peer Reflections',
      body: 'If you choose to contribute anonymously to the peer reflections pool, direct identifiers are removed before your entry is included. This is entirely your choice and can be changed at any time.',
    },
    {
      heading: 'Data Retention & Security',
      body: 'Your data is encrypted in transit and at rest. Session data is retained per your settings. You can request deletion of your account and all associated data at any time by contacting us.',
    },
    {
      heading: 'Your Rights',
      body: 'Depending on your location, you have the right to access, correct, delete, or export your data. Contact us at privacy@xolaceinc.com. We respond within 5 business days.',
    },
    {
      heading: 'Children & Changes',
      body: 'Xolace is not intended for users under 13. We may update this policy; significant changes will be communicated in the app before they take effect.',
    },
  ],
};

export const TERMS_OF_SERVICE: LegalDocument = {
  title: 'Terms of Service',
  fullUrl: 'https://xolaceinc.com/terms',
  sections: [
    {
      heading: 'What Xolace Is',
      body: 'Xolace is a personal emotional processing tool, not a healthcare provider, therapist, crisis service, or social network. Using Xolace does not create a doctor-patient or therapist-client relationship.',
    },
    {
      heading: 'Eligibility',
      body: 'You must be at least 13 years old to use Xolace. By using the app, you confirm you have the legal capacity to agree to these Terms.',
    },
    {
      heading: 'Your Responsibilities',
      body: 'Use Xolace only for lawful, personal purposes. Do not misuse the service, use automated systems, or attempt to exploit the platform. You are responsible for all activity under your account.',
    },
    {
      heading: 'AI-Generated Content',
      body: 'Reflections are generated by AI and may be incomplete or imperfect. They are not professional advice. Do not rely on them for medical, mental health, or crisis decisions.',
    },
    {
      heading: 'Your Content',
      body: 'You retain ownership of what you write. You grant us a limited license to process it to operate the service and generate reflections. Your entries are private by default.',
    },
    {
      heading: 'Limitation of Liability',
      body: 'Xolace is provided "as is." We are not liable for emotional distress or decisions made based on AI reflections. Our total liability will not exceed the amount you paid in the prior 12 months.',
    },
  ],
};
